services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - ./payload-key-pair.pem:/home/node/.ssh/payload-key-pair.pem
      - ./global-bundle.pem:/home/node/.ssh/global-bundle.pem
    working_dir: /home/node/app/
    command: >
      sh -c "apk add --no-cache openssh &&
             chmod 600 /home/node/.ssh/payload-key-pair.pem &&
             ssh -i /home/node/.ssh/payload-key-pair.pem -o StrictHostKeyChecking=no -L 27017:payloaddb-cluster.cluster-cdwoscwgopua.us-west-2.docdb.amazonaws.com:27017 ec2-user@ec2-52-13-0-85.us-west-2.compute.amazonaws.com -N &
             npm install -g pnpm@9.2.0 &&
             pnpm install &&
             pnpm dev"
    depends_on:
      - mongo
    env_file:
      - .env

  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - '27017:27017'
  #   command:
  #     - --storageEngine=wiredTiger
  #   volumes:
  #     - data:/data/db
  #   logging:
  #     driver: none

volumes:
  data:
  # pgdata:
  node_modules:
